### ISSUE TITLE
Authentication Error Can Not BOOK A SESSION

### ISSUE THREAD

**Issue by ecasilla** [airpair/airpair-com-issues#370]
<img width="1276" alt="screen shot 2016-05-02 at 11 53 36 pm" src="https://cloud.githubusercontent.com/assets/4240936/14974282/32fdbd1c-10c1-11e6-943a-8a16a9859dc3.png">

**Comment by jraczak** [comment]
Is this going to be fixed? I can't pay...

**Comment by jkresner** [comment]
Hi @ecasilla | @jraczak - I believe fixed in the lastest deploy.

Please let me know if you have troubles otherwise.
