### ISSUE TITLE
Cannot read property 'clientID' of undefined on confirm time (with PUT HTTP 400 for confirm-time)

### ISSUE THREAD

**Issue by loufranco** [airpair/airpair-com-issues#374]
I got an email with a link to a booking that needed to be confirmed.

I clicked the confirm button and on the page it said: "Cannot read property 'clientID' of undefined"

In the console, I saw this error: `index-09139a7210.js:23 PUT https://www.airpair.com/v1/api/bookings/5761f2afa5615b1100df3c9c/confirm-time 400 (Bad Request)`

**Comment by ryansb** [comment]
:+1: Happening for me as well. Did you find any workaround?

**Comment by jkresner** [comment]
@loufranco fixed, some new versions of config variables with _ characters in different places. Cheers.
